### ISSUE TITLE
OST Points, new markers and datsets

### ISSUE THREAD

**Issue by greeninfo** [greeninfo/Mobile-PitkinCountyTrails#28]
Coming soon: Point features will have a wholly new categorization system, with fewer categories. Desktop will form a working prototype of changes to be expected, which will need to be applied here.

* Replace marker icons, and rework classification code as needed.
* Front page, update blue icons with Active/Inactive states.
* Front page, update search subsystem as needed.
* Legend... not sure whether a legend will happen, pending decision.

**Comment by gregallensworth** [comment]
These are now in place, see commit d2d2252
But, some of the icons need some work.

**Comment by gregallensworth** [comment]
See commits fbdbaf6 and de6c968
Looks like we're all set.
